/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gmail.hilgardvr.fixme.view;

import com.gmail.hilgardvr.fixme.model.UserAccount;

import java.awt.event.ActionListener;
import java.util.*;
import java.text.DecimalFormat;

/**
 *
 * @author hilgard
 */
public class BrokerGui extends javax.swing.JFrame {
    
    //UserAccount ua;

    /**
     * Creates new form BrokerGui
     */
    public BrokerGui(UserAccount ua) {
        //this.ua = ua;
        initComponents();
        HoldingsComboBox.removeAllItems();
        CashBalanceTextField.setText(Double.toString(ua.getCashBalance()));
        OutputTextField.setEditable(false);
        setOutputTextField("Supported stocks are: TSLA, AMZN, MSFT and GOOGL only");
        CashBalanceTextField.setEditable(false);
        HoldingsValueTextField.setEditable(false);
        TotalAccountValueTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderLabel = new javax.swing.JLabel();
        CashBalanceLabel = new javax.swing.JLabel();
        CashBalanceTextField = new javax.swing.JTextField();
        ValueHoldingField = new javax.swing.JLabel();
        HoldingsValueTextField = new javax.swing.JTextField();
        TotalAccountValueTextField = new javax.swing.JTextField();
        TotalAccountValueField = new javax.swing.JLabel();
        HoldingsLabel = new javax.swing.JLabel();
        HoldingsComboBox = new javax.swing.JComboBox<>();
        SellVolumeTextField = new javax.swing.JTextField();
        SellButton = new javax.swing.JButton();
        ShareCodeLabel = new javax.swing.JLabel();
        BuyShareTextField = new javax.swing.JTextField();
        BuyPriceTextField = new javax.swing.JTextField();
        BuyVolumeTextField = new javax.swing.JTextField();
        BuyButton = new javax.swing.JButton();
        RefreshDataButton = new javax.swing.JToggleButton();
        OutputTextField = new javax.swing.JTextField();
        OutputLabel = new javax.swing.JLabel();
        BuyPriceLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SellPriceLabel = new javax.swing.JLabel();
        SellPriceTextField = new javax.swing.JTextField();
        //SellToggle = new javax.swing.JToggleButton();
        //BuyToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderLabel.setText("Fix-me Broker User Interface");

        CashBalanceLabel.setText("Cash balance");

        CashBalanceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashBalanceTextFieldActionPerformed(evt);
            }
        });

        ValueHoldingField.setText("Value of holdings");

        HoldingsValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoldingsValueTextFieldActionPerformed(evt);
            }
        });

        TotalAccountValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalAccountValueTextFieldActionPerformed(evt);
            }
        });

        TotalAccountValueField.setText("Total account value");

        HoldingsLabel.setText("Holdings");

        HoldingsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SellVolumeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellVolumeTextFieldActionPerformed(evt);
            }
        });

        SellButton.setText("Sell");

        ShareCodeLabel.setText("Share Code");

        BuyShareTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyShareTextFieldActionPerformed(evt);
            }
        });

        BuyPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyPriceTextFieldActionPerformed(evt);
            }
        });

        BuyVolumeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyVolumeTextFieldActionPerformed(evt);
            }
        });

        BuyButton.setText("Buy");
        BuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyButtonActionPerformed(evt);
            }
        });

        RefreshDataButton.setText("Refresh Data");

        OutputLabel.setText("Output");

        BuyPriceLabel.setText("Price");

        jLabel1.setText("Volume to Buy/Sell");

        SellPriceLabel.setText("Price");

        //SellToggle.setText("Market/Limit");

        //BuyToggle.setText("Market/Limit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CashBalanceLabel)
                                    .addComponent(ValueHoldingField)
                                    .addComponent(TotalAccountValueField))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CashBalanceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(HoldingsValueTextField)
                                    .addComponent(TotalAccountValueTextField))
                                .addGap(18, 18, 18)
                                .addComponent(RefreshDataButton))
                            .addComponent(HeaderLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(OutputLabel)
                                .addGap(49, 49, 49)
                                .addComponent(OutputTextField)))
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ShareCodeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(BuyShareTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HoldingsLabel)
                                .addGap(36, 36, 36)
                                .addComponent(HoldingsComboBox, 0, 224, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SellPriceLabel)
                            .addComponent(BuyPriceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BuyPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(SellPriceTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BuyVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BuyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                //.addComponent(BuyToggle))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(SellVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                //.addComponent(SellToggle)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CashBalanceLabel)
                    .addComponent(CashBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshDataButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValueHoldingField)
                    .addComponent(HoldingsValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalAccountValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalAccountValueField))
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoldingsLabel)
                    .addComponent(HoldingsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SellVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SellButton)
                    .addComponent(SellPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    //.addComponent(SellToggle)
                    .addComponent(SellPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShareCodeLabel)
                    .addComponent(BuyShareTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuyPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuyPriceLabel)
                    .addComponent(BuyButton)
                    //.addComponent(BuyToggle)
                    .addComponent(BuyVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutputLabel))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HoldingsValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoldingsValueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoldingsValueTextFieldActionPerformed

    private void CashBalanceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashBalanceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashBalanceTextFieldActionPerformed

    private void TotalAccountValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalAccountValueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalAccountValueTextFieldActionPerformed

    private void SellVolumeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellVolumeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SellVolumeTextFieldActionPerformed

    private void BuyShareTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyShareTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuyShareTextFieldActionPerformed

    private void BuyPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuyPriceTextFieldActionPerformed

    private void BuyVolumeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyVolumeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuyVolumeTextFieldActionPerformed

    private void BuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuyButtonActionPerformed

    public void addSellButtonListener(java.awt.event.ActionListener a) {
        SellButton.addActionListener(a);
    }

    public void addRefreshDataListener(ActionListener a) {
        RefreshDataButton.addActionListener(a);
    }

    public String getSellShare() {
        return (String)HoldingsComboBox.getSelectedItem();
    }

    public String getSellVolume() {
        return SellVolumeTextField.getText();
    }
    
    public String getSellPrice() {
        return SellPriceTextField.getText();
    }
    
    public void addBuyButtonListener(java.awt.event.ActionListener a) {
        BuyButton.addActionListener(a);
    }
    
    public String getBuyShareCode() {
        return BuyShareTextField.getText();
    }
    
    public String getBuyPrice() {
        return BuyPriceTextField.getText();
    }
    
    public String getBuyVolume() {
        return BuyVolumeTextField.getText();
    }
    
    public void setOutputTextField(String str) {
        OutputTextField.setText(str);
    }
    
    public void displayHoldings(Map<String, Integer> newMap) {
        HoldingsComboBox.removeAllItems();
        BuyPriceTextField.setText("");
        BuyVolumeTextField.setText("");
        BuyShareTextField.setText("");
        SellPriceTextField.setText("");
        SellVolumeTextField.setText("");
        for (Map.Entry<String, Integer> hold : newMap.entrySet()) {
            String stock = hold.getKey();
            Integer volume = hold.getValue();
            HoldingsComboBox.addItem(stock + " amount held: " + volume);// + "/t" + volume.toString());
        }
    }

    public void disableButtons() {
        BuyButton.setEnabled(false);
        SellButton.setEnabled(false);
        RefreshDataButton.setEnabled(false);
    }

    public void enableButtons() {
        BuyButton.setEnabled(true);
        SellButton.setEnabled(true);
        RefreshDataButton.setEnabled(true);
    }
    
    private String formatDecimals(double d) {
        DecimalFormat df = new DecimalFormat("#0.00");
        return df.format(d);
    }

    public void displayCashBalance(Double bal) {
        CashBalanceTextField.setText(formatDecimals(bal));
    }

    public void setHoldingsValue(double d) {
        HoldingsValueTextField.setText(formatDecimals(d));
    }

    public void setTotalAccountValue(double d) {
        TotalAccountValueTextField.setText(formatDecimals(d));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuyButton;
    private javax.swing.JLabel BuyPriceLabel;
    private javax.swing.JTextField BuyPriceTextField;
    private javax.swing.JTextField BuyShareTextField;
    //private javax.swing.JToggleButton BuyToggle;
    private javax.swing.JTextField BuyVolumeTextField;
    private javax.swing.JLabel CashBalanceLabel;
    private javax.swing.JTextField CashBalanceTextField;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JComboBox<String> HoldingsComboBox;
    private javax.swing.JLabel HoldingsLabel;
    private javax.swing.JTextField HoldingsValueTextField;
    private javax.swing.JLabel OutputLabel;
    private javax.swing.JTextField OutputTextField;
    private javax.swing.JToggleButton RefreshDataButton;
    private javax.swing.JButton SellButton;
    private javax.swing.JLabel SellPriceLabel;
    private javax.swing.JTextField SellPriceTextField;
    //private javax.swing.JToggleButton SellToggle;
    private javax.swing.JTextField SellVolumeTextField;
    private javax.swing.JLabel ShareCodeLabel;
    private javax.swing.JLabel TotalAccountValueField;
    private javax.swing.JTextField TotalAccountValueTextField;
    private javax.swing.JLabel ValueHoldingField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
